import type { CompanySeed } from './types'

/**
 * Empreses i conglomerats.
 *
 * L'arbre es construeix amb `parent`, de manera que una fitxa d'aplicació
 * sempre penja d'una entitat concreta (WhatsApp Ireland) i aquesta penja del
 * grup (Meta Platforms). Això permet respondre preguntes com «quantes de les
 * aplicacions que faig servir acaben al mateix grup empresarial».
 */
export const companies: CompanySeed[] = [
  /* ── Meta ── */
  {
    slug: 'meta-platforms',
    name: 'Meta Platforms',
    legalName: 'Meta Platforms, Inc.',
    description:
      'Grup propietari de Facebook, Instagram, WhatsApp, Messenger i Threads. El seu ingrés principal és la publicitat basada en el perfilat de les persones usuàries dels seus serveis.',
    headquartersCountry: 'US',
    euEstablishment: 'IE',
    leadSupervisoryAuthority: 'Data Protection Commission (Irlanda)',
    ownership: 'public',
    foundedYear: 2004,
    primaryRevenueModel: 'advertising',
    website: 'https://about.meta.com/',
    productDomains: ['facebook.com', 'instagram.com', 'threads.net', 'messenger.com', 'meta.com', 'oculus.com'],
    privacyContact: 'https://www.facebook.com/help/contact/540977946302970',
  },
  {
    slug: 'meta-platforms-ireland',
    name: 'Meta Platforms Ireland',
    legalName: 'Meta Platforms Ireland Limited',
    parent: 'meta-platforms',
    description:
      'Responsable del tractament de dades de les persones usuàries de Facebook i Instagram a la Unió Europea.',
    headquartersCountry: 'IE',
    euEstablishment: 'IE',
    leadSupervisoryAuthority: 'Data Protection Commission (Irlanda)',
    ownership: 'subsidiary',
    primaryRevenueModel: 'advertising',
    website: 'https://about.meta.com/',
  },
  {
    slug: 'whatsapp-ireland',
    name: 'WhatsApp Ireland',
    legalName: 'WhatsApp Ireland Limited',
    parent: 'meta-platforms',
    description:
      'Entitat de Meta responsable de WhatsApp a la regió europea. WhatsApp va ser adquirida per Facebook el 2014.',
    headquartersCountry: 'IE',
    euEstablishment: 'IE',
    leadSupervisoryAuthority: 'Data Protection Commission (Irlanda)',
    ownership: 'subsidiary',
    foundedYear: 2009,
    primaryRevenueModel: 'mixed',
    website: 'https://www.whatsapp.com/',
    productDomains: ['whatsapp.com'],
  },

  /* ── Alphabet ── */
  {
    slug: 'alphabet',
    name: 'Alphabet',
    legalName: 'Alphabet Inc.',
    description:
      'Societat matriu de Google, creada el 2015. Concentra el cercador, el navegador Chrome, Android, YouTube, Gmail i Maps, i és el principal intermediari publicitari del web.',
    headquartersCountry: 'US',
    ownership: 'public',
    foundedYear: 2015,
    primaryRevenueModel: 'advertising',
    website: 'https://abc.xyz/',
  },
  {
    slug: 'google',
    name: 'Google',
    legalName: 'Google LLC',
    parent: 'alphabet',
    description:
      'Filial operativa d’Alphabet que presta el cercador, Chrome, Gmail, YouTube, Maps, Drive i Android sota una única política de privadesa i un únic compte.',
    headquartersCountry: 'US',
    euEstablishment: 'IE',
    leadSupervisoryAuthority: 'Data Protection Commission (Irlanda)',
    ownership: 'subsidiary',
    foundedYear: 1998,
    primaryRevenueModel: 'advertising',
    website: 'https://about.google/',
    productDomains: ['google.com', 'youtube.com', 'gmail.com', 'blogger.com', 'android.com', 'waze.com', 'fitbit.com'],
    privacyContact: 'https://support.google.com/policies/troubleshooter/9009584',
  },
  {
    slug: 'google-ireland',
    name: 'Google Ireland',
    legalName: 'Google Ireland Limited',
    parent: 'google',
    description:
      'Responsable del tractament per als serveis de Google oferts a l’Espai Econòmic Europeu i a Suïssa.',
    headquartersCountry: 'IE',
    euEstablishment: 'IE',
    leadSupervisoryAuthority: 'Data Protection Commission (Irlanda)',
    ownership: 'subsidiary',
    primaryRevenueModel: 'advertising',
    website: 'https://about.google/',
  },

  /* ── ByteDance ── */
  {
    slug: 'bytedance',
    name: 'ByteDance',
    legalName: 'ByteDance Ltd.',
    description:
      'Grup d’origen xinès, constituït a les Illes Caiman, propietari de TikTok i de Douyin. La ubicació real de les dades europees i l’accés des de la Xina han estat objecte de decisions sancionadores.',
    headquartersCountry: 'CN',
    ownership: 'private',
    foundedYear: 2012,
    primaryRevenueModel: 'advertising',
    website: 'https://www.bytedance.com/',
    productDomains: ['tiktok.com', 'capcut.com', 'douyin.com'],
  },
  {
    slug: 'tiktok-technology',
    name: 'TikTok Technology Limited',
    legalName: 'TikTok Technology Limited',
    parent: 'bytedance',
    description:
      'Entitat irlandesa responsable del tractament de dades de TikTok a l’Espai Econòmic Europeu, juntament amb TikTok Information Technologies UK.',
    headquartersCountry: 'IE',
    euEstablishment: 'IE',
    leadSupervisoryAuthority: 'Data Protection Commission (Irlanda)',
    ownership: 'subsidiary',
    primaryRevenueModel: 'advertising',
    website: 'https://www.tiktok.com/',
  },

  /* ── Microsoft ── */
  {
    slug: 'microsoft',
    name: 'Microsoft',
    legalName: 'Microsoft Corporation',
    description:
      'Grup propietari de LinkedIn, Windows, Bing, GitHub i Azure. El seu model combina llicències i subscripcions amb un negoci publicitari creixent.',
    headquartersCountry: 'US',
    euEstablishment: 'IE',
    leadSupervisoryAuthority: 'Data Protection Commission (Irlanda)',
    ownership: 'public',
    foundedYear: 1975,
    primaryRevenueModel: 'mixed',
    website: 'https://www.microsoft.com/',
    productDomains: ['microsoft.com', 'outlook.com', 'hotmail.com', 'live.com', 'xbox.com', 'skype.com', 'github.com', 'bing.com'],
  },
  {
    slug: 'linkedin-ireland',
    name: 'LinkedIn Ireland',
    legalName: 'LinkedIn Ireland Unlimited Company',
    parent: 'microsoft',
    description:
      'Responsable del tractament de LinkedIn per a l’Espai Econòmic Europeu. LinkedIn va ser adquirida per Microsoft el 2016.',
    headquartersCountry: 'IE',
    euEstablishment: 'IE',
    leadSupervisoryAuthority: 'Data Protection Commission (Irlanda)',
    ownership: 'subsidiary',
    foundedYear: 2003,
    primaryRevenueModel: 'mixed',
    website: 'https://www.linkedin.com/',
    productDomains: ['linkedin.com'],
  },

  /* ── Amazon ── */
  {
    slug: 'amazon',
    name: 'Amazon',
    legalName: 'Amazon.com, Inc.',
    description:
      'Grup de comerç electrònic, computació al núvol, dispositius connectats i publicitat. La seva xarxa publicitària s’alimenta de l’historial de compra i navegació dins de la botiga.',
    headquartersCountry: 'US',
    euEstablishment: 'LU',
    leadSupervisoryAuthority: 'Commission nationale pour la protection des données (Luxemburg)',
    ownership: 'public',
    foundedYear: 1994,
    primaryRevenueModel: 'mixed',
    website: 'https://www.amazon.com/',
    productDomains: ['amazon.com', 'amazon.es', 'audible.com', 'twitch.tv', 'goodreads.com', 'imdb.com', 'ring.com', 'zappos.com'],
  },
  {
    slug: 'amazon-europe-core',
    name: 'Amazon Europe Core',
    legalName: 'Amazon Europe Core S.à r.l.',
    parent: 'amazon',
    description:
      'Entitat luxemburguesa corresponsable del tractament de dades de les botigues europees d’Amazon.',
    headquartersCountry: 'LU',
    euEstablishment: 'LU',
    leadSupervisoryAuthority: 'Commission nationale pour la protection des données (Luxemburg)',
    ownership: 'subsidiary',
    primaryRevenueModel: 'mixed',
    website: 'https://www.amazon.es/',
  },

  /* ── X / xAI ── */
  {
    slug: 'x-corp',
    name: 'X Corp.',
    legalName: 'X Corp.',
    parent: 'xai',
    description:
      'Empresa que opera la xarxa X, abans Twitter. Des del març de 2025 forma part de xAI, cosa que connecta la plataforma amb el desenvolupament de models d’intel·ligència artificial.',
    headquartersCountry: 'US',
    euEstablishment: 'IE',
    leadSupervisoryAuthority: 'Data Protection Commission (Irlanda)',
    ownership: 'subsidiary',
    foundedYear: 2006,
    primaryRevenueModel: 'mixed',
    website: 'https://x.com/',
    productDomains: ['twitter.com', 'x.com'],
  },
  {
    slug: 'xai',
    name: 'xAI',
    legalName: 'xAI Holdings Corp.',
    description:
      'Empresa d’intel·ligència artificial fundada el 2023, propietària del model Grok i, des del 2025, de X.',
    headquartersCountry: 'US',
    ownership: 'private',
    foundedYear: 2023,
    primaryRevenueModel: 'mixed',
    website: 'https://x.ai/',
    productDomains: ['x.ai', 'grok.com'],
  },

  /* ── Resta ── */
  {
    slug: 'netflix',
    name: 'Netflix',
    legalName: 'Netflix, Inc.',
    description:
      'Servei de vídeo per subscripció que, des del 2022, també ofereix un pla finançat amb publicitat.',
    headquartersCountry: 'US',
    euEstablishment: 'NL',
    leadSupervisoryAuthority: 'Autoriteit Persoonsgegevens (Països Baixos)',
    ownership: 'public',
    foundedYear: 1997,
    primaryRevenueModel: 'subscription',
    website: 'https://www.netflix.com/',
    productDomains: ['netflix.com'],
    privacyContact: 'privacy@netflix.com',
  },
  {
    slug: 'spotify',
    name: 'Spotify',
    legalName: 'Spotify AB',
    description:
      'Servei de música en línia amb un pla gratuït finançat amb publicitat i un pla de pagament. La seva recomanació es basa en un historial d’escolta molt detallat.',
    headquartersCountry: 'SE',
    euEstablishment: 'SE',
    leadSupervisoryAuthority: 'Integritetsskyddsmyndigheten (Suècia)',
    ownership: 'public',
    foundedYear: 2006,
    primaryRevenueModel: 'freemium',
    website: 'https://www.spotify.com/',
    productDomains: ['spotify.com'],
    privacyContact: 'privacy@spotify.com',
  },
  {
    slug: 'telegram',
    name: 'Telegram',
    legalName: 'Telegram Group Inc. / Telegram FZ-LLC',
    description:
      'Servei de missatgeria constituït a les Illes Verges Britàniques amb operació als Emirats Àrabs Units. Finançat amb subscripcions, publicitat en canals i emissions de deute.',
    headquartersCountry: 'AE',
    ownership: 'private',
    foundedYear: 2013,
    primaryRevenueModel: 'freemium',
    website: 'https://telegram.org/',
    productDomains: ['telegram.org', 't.me'],
    privacyContact: 'dpo@telegram.org',
  },
  {
    slug: 'snap',
    name: 'Snap Inc.',
    legalName: 'Snap Inc.',
    description:
      'Empresa propietària de Snapchat i de les ulleres Spectacles. Els seus ingressos provenen gairebé íntegrament de la publicitat.',
    headquartersCountry: 'US',
    euEstablishment: 'NL',
    leadSupervisoryAuthority: 'Autoriteit Persoonsgegevens (Països Baixos)',
    ownership: 'public',
    foundedYear: 2011,
    primaryRevenueModel: 'advertising',
    website: 'https://snap.com/',
    productDomains: ['snapchat.com'],
  },
  {
    slug: 'reddit',
    name: 'Reddit',
    legalName: 'Reddit, Inc.',
    description:
      'Xarxa de comunitats temàtiques amb identitat pseudònima. Cotitza en borsa des del 2024 i ha signat acords de llicència de contingut per a l’entrenament de models de llenguatge.',
    headquartersCountry: 'US',
    euEstablishment: 'IE',
    leadSupervisoryAuthority: 'Data Protection Commission (Irlanda)',
    ownership: 'public',
    foundedYear: 2005,
    primaryRevenueModel: 'advertising',
    website: 'https://www.redditinc.com/',
    productDomains: ['reddit.com'],
  },
  {
    slug: 'pinterest',
    name: 'Pinterest',
    legalName: 'Pinterest, Inc.',
    description:
      'Plataforma de descobriment visual on el catàleg d’imatges desades funciona, de fet, com una declaració d’intencions de compra.',
    headquartersCountry: 'US',
    euEstablishment: 'IE',
    leadSupervisoryAuthority: 'Data Protection Commission (Irlanda)',
    ownership: 'public',
    foundedYear: 2010,
    primaryRevenueModel: 'advertising',
    website: 'https://www.pinterest.com/',
    productDomains: ['pinterest.com'],
  },
  {
    slug: 'match-group',
    name: 'Match Group',
    legalName: 'Match Group, Inc.',
    description:
      'Grup propietari de Tinder, Hinge, OkCupid, Meetic i Plenty of Fish. Concentra bona part del mercat de les cites en línia i comparteix dades entre les seves marques.',
    headquartersCountry: 'US',
    euEstablishment: 'IE',
    leadSupervisoryAuthority: 'Data Protection Commission (Irlanda)',
    ownership: 'public',
    foundedYear: 1995,
    primaryRevenueModel: 'freemium',
    website: 'https://mtch.com/',
    productDomains: ['tinder.com', 'okcupid.com', 'match.com', 'pof.com', 'hinge.co', 'meetic.es', 'ourtime.com'],
  },
  {
    slug: 'delivery-hero',
    name: 'Delivery Hero',
    legalName: 'Delivery Hero SE',
    description:
      'Grup alemany de repartiment a domicili, propietari de Glovo des del 2022.',
    headquartersCountry: 'DE',
    euEstablishment: 'DE',
    ownership: 'public',
    foundedYear: 2011,
    primaryRevenueModel: 'mixed',
    website: 'https://www.deliveryhero.com/',
    productDomains: ['deliveryhero.com', 'foodpanda.com', 'pedidosya.com'],
  },
  {
    slug: 'glovo',
    name: 'Glovo',
    legalName: 'Glovoapp23, S.A.',
    parent: 'delivery-hero',
    description:
      'Plataforma de repartiment a domicili amb seu a Barcelona. Tracta dades de tres col·lectius alhora: clientela, comerços i repartidors.',
    headquartersCountry: 'ES',
    euEstablishment: 'ES',
    leadSupervisoryAuthority: 'Agencia Española de Protección de Datos',
    ownership: 'subsidiary',
    foundedYear: 2015,
    primaryRevenueModel: 'mixed',
    website: 'https://glovoapp.com/',
    productDomains: ['glovoapp.com'],
    privacyContact: 'gdpr@glovoapp.com',
  },
  {
    slug: 'signal-foundation',
    name: 'Signal Technology Foundation',
    legalName: 'Signal Technology Foundation',
    description:
      'Fundació sense ànim de lucre nord-americana que desenvolupa Signal. Es finança amb donacions i amb un préstec inicial de Brian Acton, cofundador de WhatsApp.',
    headquartersCountry: 'US',
    ownership: 'nonprofit',
    foundedYear: 2018,
    primaryRevenueModel: 'donations',
    website: 'https://signal.org/',
    productDomains: ['signal.org'],
  },
  {
    slug: 'proton',
    name: 'Proton',
    legalName: 'Proton AG',
    description:
      'Empresa suïssa de serveis xifrats de correu, calendari, emmagatzematge i VPN. Des del 2024 està controlada per la Fundació Proton, sense ànim de lucre.',
    headquartersCountry: 'CH',
    ownership: 'nonprofit',
    foundedYear: 2014,
    primaryRevenueModel: 'freemium',
    website: 'https://proton.me/',
    productDomains: ['proton.me', 'protonmail.com'],
    privacyContact: 'privacy@proton.me',
  },
  {
    slug: 'duckduckgo',
    name: 'DuckDuckGo',
    legalName: 'DuckDuckGo, Inc.',
    description:
      'Empresa nord-americana que ofereix un cercador i un navegador orientats a no construir perfils. Es finança amb publicitat contextual, sense historial de cerca.',
    headquartersCountry: 'US',
    ownership: 'private',
    foundedYear: 2008,
    primaryRevenueModel: 'advertising',
    website: 'https://duckduckgo.com/',
    productDomains: ['duckduckgo.com'],
  },
  {
    slug: 'mozilla-foundation',
    name: 'Mozilla Foundation',
    legalName: 'Mozilla Foundation',
    description:
      'Fundació sense ànim de lucre propietària de Mozilla Corporation. Manté Firefox com a alternativa independent als navegadors dels grans grups.',
    headquartersCountry: 'US',
    ownership: 'nonprofit',
    foundedYear: 2003,
    primaryRevenueModel: 'donations',
    website: 'https://foundation.mozilla.org/',
    productDomains: ['mozilla.org'],
  },
  {
    slug: 'mozilla-corporation',
    name: 'Mozilla Corporation',
    legalName: 'Mozilla Corporation',
    parent: 'mozilla-foundation',
    description:
      'Filial que desenvolupa Firefox. La major part dels seus ingressos prové de l’acord perquè Google sigui el cercador per defecte, una dependència reconeguda públicament.',
    headquartersCountry: 'US',
    euEstablishment: 'DE',
    ownership: 'subsidiary',
    foundedYear: 2005,
    primaryRevenueModel: 'mixed',
    website: 'https://www.mozilla.org/',
    productDomains: ['firefox.com'],
    privacyContact: 'compliance@mozilla.com',
  },
  {
    slug: 'brave-software',
    name: 'Brave Software',
    legalName: 'Brave Software, Inc.',
    description:
      'Empresa nord-americana que desenvolupa el navegador Brave i el cercador Brave Search, amb bloqueig de rastrejadors activat per defecte.',
    headquartersCountry: 'US',
    ownership: 'private',
    foundedYear: 2015,
    primaryRevenueModel: 'mixed',
    website: 'https://brave.com/',
    productDomains: ['brave.com'],
    privacyContact: 'privacy@brave.com',
  },
]
