/**
 * FITXER GENERAT AUTOMÀTICAMENT. NO L'EDITIS A MÀ.
 *
 * Qualsevol canvi fet aquí es perdrà la propera vegada que algú executi:
 *
 *     pnpm build-wordlist
 *
 * El generador és `scripts/build-wordlist.ts` i allà hi ha explicat, criteri
 * per criteri, per què cada paraula hi és i per què n'han quedat fora tantes
 * altres.
 *
 * Què és això: la llista de paraules catalanes amb què es construeixen les
 * frases de pas, a l'estil de les llistes «diceware» de l'Electronic Frontier
 * Foundation. Són noms comuns en singular, escrits només amb lletres de la a
 * a la z perquè es puguin teclejar a qualsevol teclat, de 4 a 11
 * lletres, amb les 4 primeres lletres úniques dins de la llista, i
 * triades d'entre les més corrents del català.
 *
 * Per què n'hi ha exactament 2048 i no 2000 ni 2500: 2048 és 2^11, de manera
 * que cada paraula aporta exactament 11 bits d'entropia. Amb qualsevol altra
 * mida la força d'una frase seria log2(mida) per paraula, un nombre amb
 * decimals que obliga a arrodonir i converteix el càlcul en una aproximació.
 * Amb 2048 el compte és exacte i mental: sis paraules són 66 bits, set en són
 * 77. També permet treure 11 bits nets de `crypto.getRandomValues` sense
 * introduir biaix de mòdul.
 *
 * Font de les paraules i llicències: vegeu WORDLIST_META.
 */

export const WORDLIST_CA: readonly string[] = [
  'abastament', 'abdomen', 'abeurador', 'abillament', 'abisme', 'abocador', 'abonament', 'abordatge',
  'abreviatura', 'abric', 'absorbent', 'absurd', 'abundor', 'acabament', 'accent', 'accionista',
  'aclariment', 'acoblament', 'acolliment', 'acompliment', 'acord', 'acostament', 'acta', 'acte',
  'activitat', 'actor', 'actualitat', 'acusador', 'additiu', 'adepte', 'adhesiu', 'adjectiu',
  'adjunt', 'admirador', 'adob', 'adolescent', 'adorador', 'adrenalina', 'adult', 'advertiment',
  'aeri', 'aeroport', 'afecte', 'afer', 'afinitat', 'afirmativa', 'afluent', 'agent',
  'agitador', 'agricultura', 'agrupament', 'agudesa', 'agulla', 'ahir', 'aigua', 'aire',
  'aixeta', 'aixopluc', 'ajornament', 'ajuda', 'ajuntament', 'ajut', 'alarma', 'albada',
  'albercoc', 'alcalde', 'alcova', 'alegria', 'aleta', 'alfabet', 'alga', 'algorisme',
  'aliatge', 'aliment', 'alleujament', 'alliberador', 'allotjament', 'almanac', 'almoina', 'alpinista',
  'alquimista', 'altaveu', 'alternativa', 'altitud', 'alto', 'altruista', 'alumne', 'amabilitat',
  'amagatall', 'amant', 'amargament', 'amateur', 'ambaixador', 'ambient', 'ambre', 'amfiteatre',
  'amic', 'amiguet', 'ampit', 'amplada', 'ampolla', 'amulet', 'anagrama', 'analista',
  'anarquista', 'anatomia', 'anca', 'andana', 'androide', 'aneguet', 'anell', 'angelet',
  'anguila', 'anhel', 'animal', 'aniversari', 'annex', 'anomalia', 'anonimat', 'anormal',
  'antagonisme', 'antena', 'antic', 'antologia', 'anual', 'anunci', 'anxova', 'aparell',
  'apatia', 'aperitiu', 'aplaudiment', 'aplec', 'apocalipsi', 'apogeu', 'apologia', 'aposta',
  'apotecari', 'aprenent', 'apropament', 'aptitud', 'apunt', 'arada', 'arbitratge', 'arbre',
  'arbust', 'arca', 'ardor', 'arena', 'aresta', 'argenteria', 'argot', 'argument',
  'armari', 'armilla', 'aroma', 'arpa', 'arponer', 'arquitecte', 'arracada', 'arrel',
  'artefacte', 'article', 'arxiu', 'ascensor', 'aspecte', 'aspirant', 'aspre', 'assaig',
  'assemblea', 'assistent', 'assoliment', 'assumpte', 'asteroide', 'astre', 'atacant', 'ataronjat',
  'aterratge', 'atleta', 'atmosfera', 'atorgament', 'atractiu', 'atreviment', 'atribut', 'atuell',
  'atzar', 'audiovisual', 'auge', 'augment', 'aula', 'auricular', 'austeritat', 'autor',
  'avalot', 'avantatge', 'avaria', 'avatar', 'avellana', 'aventura', 'avet', 'aviador',
  'avidesa', 'avinentesa', 'avioneta', 'badall', 'bagatge', 'bagul', 'baia', 'baix',
  'bajanada', 'balconada', 'baldufa', 'balena', 'ball', 'balneari', 'baluard', 'banalitat',
  'banc', 'banda', 'banquet', 'baptisme', 'baralla', 'barberia', 'barcassa', 'baronia',
  'barqueta', 'barranc', 'base', 'bassal', 'bastidor', 'batec', 'batlle', 'batuta',
  'batxillerat', 'baula', 'bava', 'beca', 'bedoll', 'beina', 'beisbol', 'bellesa',
  'benaurat', 'benefici', 'benzina', 'bergant', 'besavi', 'bescuit', 'bestiar', 'beta',
  'betum', 'beuratge', 'bevedor', 'biaix', 'biblioteca', 'bicicleta', 'biennal', 'biga',
  'bigoti', 'billar', 'bingo', 'binocle', 'biografia', 'biologia', 'biquini', 'bisbat',
  'bistec', 'bitllet', 'bitxo', 'blancor', 'bloc', 'blues', 'boca', 'bocinet',
  'boda', 'bodega', 'bogeria', 'bohemi', 'boig', 'boina', 'boirina', 'boja',
  'bola', 'boleta', 'bolquer', 'bomber', 'bondat', 'bonhomia', 'borinot', 'borrissol',
  'borsa', 'bossa', 'botiga', 'boxador', 'boxejador', 'bracet', 'branqueta', 'brasa',
  'brava', 'bretxa', 'breu', 'brevetat', 'brida', 'brigada', 'brillant', 'brioix',
  'brisa', 'brolla', 'broma', 'bronqui', 'brot', 'brou', 'bruixa', 'brusa',
  'bucle', 'budisme', 'bufanda', 'bufet', 'bugada', 'buida', 'buit', 'bulevard',
  'bungalou', 'burgesia', 'burleta', 'busca', 'bust', 'butaca', 'cabal', 'cabdal',
  'cabell', 'cabina', 'cable', 'cabrit', 'cacau', 'cactus', 'cadet', 'caducitat',
  'cafeteria', 'caixa', 'calaix', 'calb', 'calculador', 'calda', 'calendari', 'califa',
  'calmant', 'calor', 'calze', 'camarada', 'cambrer', 'camisa', 'campament', 'camuflatge',
  'canalla', 'canceller', 'candidat', 'canelobre', 'cangur', 'canoa', 'cansament', 'cantonada',
  'canvi', 'caoba', 'caos', 'capa', 'capdamunt', 'capelleta', 'capital', 'caporal',
  'caprici', 'capsa', 'captura', 'caputxa', 'capvespre', 'caqui', 'cara', 'carbassa',
  'carcassa', 'card', 'carena', 'caricatura', 'carn', 'carpeta', 'carretera', 'carta',
  'carxofa', 'casa', 'casc', 'caseta', 'casino', 'casquet', 'cassola', 'casteller',
  'casualitat', 'catalanitat', 'catedral', 'catifa', 'catorze', 'catxalot', 'causa', 'cautela',
  'cavall', 'caverna', 'cavitat', 'ceba', 'cedre', 'cegament', 'celebritat', 'cella',
  'celobert', 'cendrer', 'cens', 'cent', 'ceptre', 'cercle', 'cerimonial', 'certesa',
  'cervell', 'cessament', 'cicle', 'cigarreta', 'cigne', 'cilindre', 'cimera', 'cinc',
  'cinema', 'cinglera', 'cinquanta', 'circuit', 'cirerer', 'ciri', 'cirurgia', 'cistell',
  'cita', 'ciutadania', 'civada', 'clam', 'clan', 'clapa', 'claror', 'classe',
  'clatell', 'clau', 'claveguera', 'clergat', 'client', 'clima', 'clip', 'clivella',
  'cloenda', 'clorur', 'closca', 'club', 'coautor', 'cobertura', 'cobla', 'cobrellit',
  'cocodril', 'codi', 'coeficient', 'coet', 'cofre', 'cofundador', 'cognom', 'cogombre',
  'coixinet', 'cola', 'coliflor', 'colla', 'color', 'columna', 'colze', 'comarca',
  'combat', 'comercial', 'comissari', 'comoditat', 'compte', 'comtat', 'comunitat', 'concepte',
  'conductor', 'coneixement', 'conflicte', 'congelador', 'conillet', 'conjunt', 'conquesta', 'conreu',
  'consell', 'contacte', 'convers', 'copa', 'copet', 'copista', 'coqueteria', 'coratge',
  'corba', 'corda', 'coreografia', 'corn', 'corona', 'corporal', 'corrent', 'corsari',
  'cort', 'cosa', 'cosmos', 'cosset', 'costum', 'cota', 'cotilla', 'cotxe',
  'covard', 'cove', 'creador', 'creditor', 'creixement', 'cremallera', 'crepuscle', 'cresta',
  'creuer', 'criatura', 'crida', 'crinera', 'criptograma', 'crisi', 'crit', 'croissant',
  'cromo', 'cronista', 'croquis', 'crosta', 'crustaci', 'cubell', 'cuca', 'cucut',
  'cuidador', 'cuiner', 'cuir', 'cuixa', 'culet', 'cullera', 'culpa', 'cultura',
  'cuneta', 'cura', 'curiositat', 'curs', 'curull', 'cutis', 'daltabaix', 'dama',
  'dansa', 'dard', 'darreria', 'data', 'davanter', 'debat', 'decenni', 'decimal',
  'declivi', 'decor', 'decret', 'decurs', 'defensa', 'deixeble', 'delicadesa', 'delta',
  'demanda', 'demografia', 'denominador', 'densitat', 'dent', 'departament', 'dependent', 'depredador',
  'depurador', 'desafiament', 'descendent', 'desembre', 'desgrat', 'desig', 'desmai', 'desnivell',
  'desordre', 'despatx', 'destresa', 'desviament', 'detall', 'detectiu', 'detractor', 'deute',
  'devot', 'diada', 'diagonal', 'dialecte', 'diamant', 'diapositiva', 'diari', 'dibuix',
  'diccionari', 'dictamen', 'dida', 'dieta', 'diferencial', 'digestiu', 'digital', 'dignitat',
  'dijous', 'dilema', 'dilluns', 'dimarts', 'dimecres', 'dinastia', 'diner', 'dinou',
  'diploma', 'dipositari', 'director', 'dirigent', 'disbarat', 'discurs', 'disfressa', 'disgust',
  'disputa', 'dissabte', 'districte', 'divan', 'divendres', 'divinitat', 'divuit', 'doble',
  'docent', 'doctrina', 'document', 'dogma', 'dolcesa', 'dolent', 'doll', 'domini',
  'dona', 'doneta', 'dormitori', 'dors', 'dosi', 'dossier', 'dotze', 'dragona',
  'drama', 'drap', 'drassana', 'drecera', 'drenatge', 'dret', 'dual', 'duana',
  'dubte', 'duna', 'duquessa', 'duresa', 'dutxa', 'ecologista', 'economia', 'ecosistema',
  'edat', 'edicte', 'edifici', 'editorial', 'educador', 'efecte', 'egipci', 'egoista',
  'eixam', 'eixut', 'elasticitat', 'elector', 'elefant', 'elegia', 'element', 'elit',
  'elixir', 'elogi', 'embassament', 'emblema', 'embolic', 'embut', 'emigrant', 'emirat',
  'emissor', 'empat', 'emperador', 'empleat', 'empresari', 'enamorament', 'encanteri', 'encert',
  'enciam', 'enclavament', 'encontre', 'encreuament', 'enderroc', 'enduriment', 'energia', 'enfilall',
  'enfocament', 'engruna', 'enhorabona', 'enigma', 'enlairament', 'enquesta', 'enrenou', 'enriquiment',
  'ensurt', 'enteniment', 'entitat', 'entrenador', 'entusiasta', 'enuig', 'envergadura', 'enviament',
  'enzim', 'episodi', 'epopeia', 'equip', 'ermita', 'erotisme', 'error', 'erudit',
  'esbarjo', 'escalfor', 'escena', 'esclat', 'escola', 'escriptor', 'escut', 'esfera',
  'esfinx', 'esgotament', 'esgrima', 'esmalt', 'esmena', 'esnob', 'espatlla', 'esperit',
  'espiritual', 'esplendor', 'esport', 'esprai', 'espurna', 'esquema', 'establiment', 'estel',
  'estil', 'estona', 'estranger', 'estudi', 'etapa', 'etern', 'etimologia', 'etiqueta',
  'eucaristia', 'eufemisme', 'euga', 'eunuc', 'europeu', 'evasiva', 'exactitud', 'exalcalde',
  'examen', 'excavador', 'excedent', 'excitant', 'exclusiva', 'excusa', 'executiu', 'exemple',
  'exercici', 'exministre', 'expert', 'explorador', 'exponent', 'expresident', 'exterior', 'extrem',
  'fabricant', 'faceta', 'factura', 'facultatiu', 'fada', 'fadrina', 'faixa', 'falange',
  'faldilla', 'fall', 'falsedat', 'falta', 'fama', 'familiar', 'fanal', 'fang',
  'fantasia', 'farcell', 'fardell', 'farina', 'farmaciola', 'farratge', 'farsa', 'fart',
  'fascicle', 'fase', 'fatal', 'faula', 'fauna', 'favor', 'feble', 'febrer',
  'fecunditat', 'feina', 'feix', 'femella', 'feminista', 'fenomen', 'fera', 'ferma',
  'ferrocarril', 'fertilitat', 'ferum', 'fervor', 'fesomia', 'festa', 'fetge', 'fetiller',
  'fiador', 'fibra', 'fidelitat', 'figura', 'fila', 'filera', 'filferro', 'filial',
  'fill', 'film', 'filosofia', 'filtre', 'final', 'finca', 'finestra', 'finor',
  'fiord', 'fira', 'firma', 'fiscal', 'fisiologia', 'fisonomia', 'fissura', 'fitxa',
  'flabiol', 'flaire', 'flama', 'flanc', 'flaquesa', 'flassada', 'flauta', 'fleca',
  'fletxa', 'floc', 'floreta', 'flota', 'fluix', 'fluorescent', 'flux', 'foca',
  'focus', 'foguera', 'foli', 'follet', 'fonament', 'fonda', 'foneria', 'fong',
  'forat', 'forense', 'forma', 'forquilla', 'fortalesa', 'foscor', 'foto', 'frac',
  'fragment', 'franja', 'frase', 'fraternitat', 'frec', 'fred', 'frega', 'fresca',
  'frivolitat', 'front', 'fruit', 'fuet', 'fuga', 'fulgor', 'fulla', 'fumador',
  'funcionari', 'fundador', 'furgoneta', 'fusta', 'futbol', 'futur', 'gabinet', 'gala',
  'galeria', 'gallina', 'galta', 'gamba', 'gana', 'ganxo', 'garantia', 'garbuix',
  'garfi', 'gargot', 'garita', 'garlanda', 'garrafa', 'garsa', 'gasa', 'gasela',
  'gasolina', 'gastronomia', 'gatet', 'gatzara', 'gavardina', 'gegant', 'gelatina', 'gelosia',
  'gendre', 'general', 'geni', 'gent', 'geografia', 'geologia', 'geometria', 'gerani',
  'gerent', 'germanet', 'gerra', 'gespa', 'gest', 'gingebre', 'glacera', 'gleva',
  'globus', 'glop', 'gnom', 'gola', 'golejador', 'golf', 'goma', 'gorja',
  'gorra', 'gosadia', 'gota', 'goteta', 'govern', 'gracieta', 'gradual', 'graella',
  'grafit', 'gram', 'granja', 'grapa', 'gratitud', 'gravetat', 'greix', 'gremi',
  'gresca', 'greu', 'grill', 'gripau', 'grisor', 'groc', 'grollera', 'gronxador',
  'gropa', 'grossa', 'gruix', 'grumoll', 'grup', 'gruta', 'guant', 'guarniment',
  'guatlla', 'guineu', 'guionista', 'guirigall', 'guitarra', 'guru', 'guspira', 'gust',
  'habitant', 'hamburguesa', 'handbol', 'hangar', 'harmonia', 'havanera', 'hegemonia', 'hemisferi',
  'herald', 'herba', 'hereu', 'heroi', 'heura', 'hidrogen', 'higiene', 'himne',
  'hipnosi', 'hipoteca', 'hippie', 'hisenda', 'historiador', 'hivernacle', 'home', 'honestedat',
  'honor', 'honradesa', 'hoquei', 'hora', 'horda', 'horitzontal', 'hormona', 'horst',
  'hort', 'hospitalari', 'hoste', 'hotel', 'humanitat', 'humit', 'humor', 'iaio',
  'iceberg', 'icona', 'idea', 'identitat', 'ideologia', 'idioma', 'ignorant', 'igualtat',
  'illot', 'imant', 'imatge', 'imitador', 'immensitat', 'immigrant', 'immoble', 'immunitat',
  'impacte', 'imperi', 'impossible', 'impressor', 'impuls', 'inactivitat', 'incertesa', 'incident',
  'inconscient', 'increment', 'individu', 'indret', 'industrial', 'infant', 'inferior', 'infinit',
  'informe', 'ingredient', 'iniciativa', 'innovador', 'input', 'inquietud', 'insecte', 'inspector',
  'instant', 'insult', 'interior', 'intimitat', 'intriga', 'inversor', 'iogurt', 'ironia',
  'irregular', 'irritant', 'itinerari', 'ivori', 'jaciment', 'jade', 'jaguar', 'jaqueta',
  'jardiner', 'jerarquia', 'jersei', 'joguina', 'joia', 'joier', 'jornada', 'joventut',
  'judici', 'jugador', 'juliol', 'jungla', 'junta', 'jurament', 'jurista', 'juvenil',
  'laberint', 'laboratori', 'lacai', 'laic', 'lament', 'lampista', 'lapse', 'larva',
  'lateral', 'latitud', 'lavabo', 'lectura', 'legalitat', 'legislatura', 'lema', 'lent',
  'liberal', 'liceu', 'licor', 'lideratge', 'limusina', 'lingot', 'liquiditat', 'literatura',
  'litigi', 'litoral', 'litre', 'llacet', 'lladruc', 'llamp', 'llana', 'llapis',
  'llar', 'llauna', 'llavor', 'llebrer', 'llegenda', 'llei', 'llengua', 'lleopard',
  'llesta', 'lletra', 'lleu', 'llevador', 'llibre', 'lligam', 'llimonada', 'llindar',
  'llista', 'llit', 'lliura', 'lloc', 'lloguer', 'llom', 'llonganissa', 'lloro',
  'llotja', 'lluentor', 'lluita', 'localitat', 'locomotora', 'locutor', 'logo', 'lona',
  'longitud', 'loteria', 'lucidesa', 'lupa', 'luxe', 'maduresa', 'magatzem', 'magistrat',
  'magnitud', 'magrana', 'maig', 'mainada', 'majestat', 'major', 'maleta', 'mallorquina',
  'malnom', 'maluc', 'mamut', 'manament', 'mandat', 'maneta', 'manifest', 'manobre',
  'manso', 'manta', 'manual', 'maori', 'mapa', 'maquillatge', 'marbre', 'marcador',
  'mare', 'marge', 'marit', 'maror', 'marrec', 'marxa', 'mascota', 'masia',
  'massatge', 'matador', 'material', 'matiner', 'matoll', 'matrimoni', 'meandre', 'mecanisme',
  'mecenes', 'medalla', 'medi', 'medusa', 'meitat', 'melindro', 'melmelada', 'melodia',
  'membre', 'memorial', 'menjador', 'menor', 'ment', 'menut', 'mercat', 'meritori',
  'merla', 'mescla', 'mestressa', 'mesura', 'metall', 'meteorit', 'metgessa', 'metodologia',
  'metro', 'metxa', 'mica', 'mico', 'microbi', 'mida', 'migcampista', 'migdia',
  'migjorn', 'miler', 'militant', 'millora', 'mineral', 'ministre', 'minoria', 'minut',
  'miratge', 'missatge', 'misteri', 'mite', 'mitja', 'mitologia', 'mobiliari', 'moble',
  'mocador', 'moda', 'model', 'modista', 'moixaina', 'molsa', 'moment', 'monarca',
  'monestir', 'mongeta', 'monitor', 'monotonia', 'mont', 'monument', 'moqueta', 'moral',
  'morena', 'morfologia', 'morter', 'mosaic', 'mosquit', 'mosso', 'mostra', 'motel',
  'motiu', 'motlle', 'motor', 'motxilla', 'moviment', 'multitud', 'municipi', 'muntatge',
  'mural', 'muret', 'murmuri', 'musa', 'muscle', 'museu', 'mussol', 'nadiu',
  'naixement', 'nano', 'nariu', 'narrativa', 'nasal', 'nata', 'natural', 'navalla',
  'navegant', 'navili', 'nebulosa', 'nedador', 'negativa', 'negligent', 'negoci', 'negre',
  'neguit', 'nervi', 'netedat', 'neurona', 'neutre', 'nevera', 'nineta', 'nissaga',
  'nitrogen', 'nivell', 'noble', 'nocturn', 'node', 'noiet', 'nombre', 'nomenament',
  'noranta', 'normal', 'nosa', 'nota', 'noticiari', 'notorietat', 'nounat', 'nouvingut',
  'novembre', 'nuca', 'nucli', 'nutrient', 'nuvi', 'nuvolada', 'oasi', 'obaga',
  'obertura', 'obesitat', 'objecte', 'oblit', 'obra', 'obrer', 'observador', 'obstacle',
  'occident', 'ocell', 'ocre', 'octava', 'ocular', 'ocupant', 'odissea', 'ofec',
  'oferiment', 'oficial', 'ofrena', 'ogre', 'oient', 'oleoducte', 'olfacte', 'oliverar',
  'oller', 'olor', 'ombra', 'omega', 'onada', 'oncle', 'onze', 'operador',
  'oponent', 'oportunitat', 'opositor', 'optimista', 'oracle', 'orador', 'oratori', 'orde',
  'ordinador', 'ordre', 'orella', 'oreneta', 'orfe', 'organisme', 'orgue', 'oriental',
  'orifici', 'origen', 'ornament', 'orquestra', 'ortodox', 'ostra', 'oxigen', 'pacient',
  'pacte', 'padrina', 'paella', 'pagament', 'pagesia', 'paio', 'paisatge', 'pala',
  'paleta', 'pallasso', 'palmell', 'pancarta', 'panet', 'panorama', 'pansa', 'pantalla',
  'panxa', 'papa', 'paper', 'paquet', 'paraula', 'parc', 'pardal', 'pare',
  'paritat', 'parpella', 'parquet', 'parrac', 'part', 'parvulari', 'pasqua', 'passi',
  'pasta', 'patata', 'patent', 'pati', 'patologia', 'patrimoni', 'patufet', 'pausa',
  'pauta', 'paviment', 'peatge', 'pebrot', 'pedagogia', 'pedestal', 'pediatre', 'pedreta',
  'peixet', 'pelatge', 'pell', 'peluda', 'pendent', 'penediment', 'penic', 'penjant',
  'penombra', 'pensament', 'percentatge', 'perdiu', 'perfil', 'periodista', 'permanent', 'pernil',
  'perol', 'perplexitat', 'perruca', 'persona', 'perxa', 'peso', 'pesquera', 'pesseta',
  'petaca', 'petitesa', 'petroli', 'petxina', 'piano', 'picarol', 'picor', 'pidolaire',
  'pigment', 'pijama', 'pilastra', 'pilota', 'pinacle', 'pinso', 'pintura', 'pinzell',
  'pioner', 'pipa', 'pirata', 'piscina', 'pissarra', 'pista', 'placa', 'plaer',
  'planta', 'platja', 'plec', 'plena', 'ploma', 'plugim', 'pluja', 'plural',
  'pluvial', 'poble', 'pobre', 'poema', 'poesia', 'poeta', 'policia', 'pollastre',
  'polsera', 'poltre', 'polze', 'pompa', 'popularitat', 'porcellana', 'porpra', 'porquet',
  'portaveu', 'porxo', 'positiu', 'possible', 'posterior', 'pota', 'potencial', 'practicant',
  'precedent', 'predicador', 'prefecte', 'pregunta', 'preliminar', 'premi', 'preparatiu', 'president',
  'pretext', 'preu', 'primavera', 'principal', 'prioritat', 'prisma', 'privilegi', 'proa',
  'problema', 'procediment', 'producte', 'proesa', 'professor', 'programa', 'projecte', 'promotor',
  'pronom', 'propi', 'prosa', 'protesta', 'prova', 'proximitat', 'psicologia', 'punt',
  'pupitre', 'quadre', 'qualitat', 'quantitat', 'quaranta', 'quatre', 'queixa', 'quietud',
  'quilo', 'quimera', 'quinze', 'quiosc', 'quitxalla', 'quocient', 'quota', 'racional',
  'raconet', 'radar', 'radical', 'raig', 'rajola', 'ramaderia', 'rampa', 'rancor',
  'rang', 'ranxo', 'raonament', 'rapidesa', 'raresa', 'rasclet', 'rastre', 'ratlla',
  'ratpenat', 'ratxa', 'rave', 'reactor', 'realitat', 'rebaixa', 'rebel', 'rebost',
  'recanvi', 'recerca', 'recinte', 'reclutament', 'record', 'rector', 'recurs', 'redactor',
  'redemptor', 'reducte', 'referent', 'refineria', 'reflex', 'reforma', 'refresc', 'refugi',
  'regal', 'registre', 'regla', 'regne', 'regulador', 'reialme', 'reixa', 'relatiu',
  'rellotge', 'remer', 'remor', 'renaixement', 'renda', 'renglera', 'renovador', 'rentadora',
  'repartiment', 'repertori', 'reportatge', 'reproductor', 'repte', 'requisit', 'rerefons', 'reserva',
  'residu', 'responsable', 'resta', 'resum', 'retard', 'retina', 'retoc', 'retrat',
  'revelador', 'revisor', 'revolta', 'rialla', 'rierol', 'rigidesa', 'rigor', 'rima',
  'rinoceront', 'riquesa', 'risc', 'ritme', 'ritual', 'riuada', 'rival', 'roba',
  'robot', 'rodalia', 'rodet', 'rondalla', 'rosegador', 'rossa', 'rostre', 'rotatiu',
  'rotllo', 'rotonda', 'rovell', 'rubor', 'rudesa', 'rugbi', 'ruleta', 'rumb',
  'rumor', 'runa', 'ruptura', 'rusc', 'ruta', 'rutina', 'sabatilla', 'sabor',
  'sabre', 'sacre', 'safata', 'safir', 'sagrament', 'salari', 'salina', 'salsa',
  'salva', 'samarreta', 'sandvitx', 'sanejament', 'sanitari', 'sant', 'sarau', 'sardana',
  'sargantana', 'sarsuela', 'savi', 'saxo', 'secret', 'sector', 'secundari', 'seda',
  'sedentari', 'sediment', 'seductor', 'segador', 'segell', 'segle', 'segment', 'seguretat',
  'seient', 'seixanta', 'selecta', 'sella', 'semblant', 'semestre', 'seminari', 'senador',
  'senglar', 'sensual', 'sentiment', 'senzillesa', 'sequedat', 'serenitat', 'seriositat', 'serp',
  'serralada', 'servei', 'setanta', 'setembre', 'setmana', 'setze', 'severitat', 'sexe',
  'sidra', 'signe', 'silenci', 'silueta', 'simbolisme', 'simetria', 'simfonia', 'similitud',
  'simpatia', 'simulacre', 'sina', 'sinceritat', 'singular', 'sintonia', 'sirena', 'sistema',
  'sivella', 'sobirania', 'sobra', 'societat', 'sodi', 'sogra', 'solapa', 'solc',
  'solemnitat', 'solitari', 'solstici', 'solter', 'solvent', 'somiador', 'somni', 'sonata',
  'sonda', 'sonet', 'sonoritat', 'sopa', 'soprano', 'sord', 'soroll', 'sorra',
  'sospita', 'sostre', 'suavitat', 'subdirector', 'subhasta', 'subjecte', 'sublim', 'subproducte',
  'substitut', 'suburbi', 'successor', 'sucursal', 'suficient', 'sufragi', 'suggeriment', 'suma',
  'suor', 'superior', 'suplement', 'suport', 'surrealista', 'taca', 'tacte', 'tafaneria',
  'talent', 'tall', 'talonari', 'talp', 'tamboret', 'tanca', 'tanda', 'tango',
  'tapa', 'tapisseria', 'taquilla', 'tara', 'tarda', 'targeta', 'tarima', 'taronja',
  'tartana', 'tasca', 'tatuatge', 'taula', 'taverna', 'taxa', 'taxi', 'teatre',
  'teclat', 'tecnologia', 'tedi', 'tela', 'televisor', 'tema', 'temeritat', 'temor',
  'temps', 'tenacitat', 'tenda', 'tenista', 'tennis', 'tenor', 'tentacle', 'teologia',
  'teoria', 'terapeuta', 'tercera', 'terme', 'terra', 'tesi', 'testimoni', 'tetera',
  'teula', 'text', 'tiet', 'tija', 'timbre', 'timidesa', 'tinent', 'tinta',
  'tipologia', 'tipus', 'tiquet', 'tirador', 'tisora', 'titella', 'titularitat', 'tobogan',
  'tocador', 'tomb', 'tonalitat', 'tongada', 'torero', 'torneig', 'tors', 'tortuga',
  'torxa', 'total', 'tovallola', 'toxicitat', 'tractament', 'traductor', 'trajecte', 'tram',
  'tranquil', 'trasllat', 'travessa', 'treball', 'tremolor', 'trenta', 'tresor', 'tretze',
  'treva', 'tribunal', 'trident', 'trienni', 'trilogia', 'trimestre', 'trineu', 'triomf',
  'triple', 'trist', 'troballa', 'trofeu', 'trompeta', 'tron', 'tropa', 'trosset',
  'truca', 'truita', 'tulipa', 'turbant', 'turisme', 'turmell', 'turonet', 'turquesa',
  'ullera', 'unanimitat', 'ungla', 'uniforme', 'unitat', 'universitat', 'urbanisme', 'urna',
  'urpa', 'usuari', 'utensili', 'utilitat', 'utopia', 'vaca', 'vacuna', 'vaga',
  'vainilla', 'vaixell', 'valentia', 'validesa', 'vals', 'vanitat', 'vapor', 'vara',
  'vareta', 'variable', 'vassall', 'vector', 'vegada', 'vegetal', 'vehicle', 'veler',
  'vell', 'velocitat', 'vena', 'vencedor', 'venda', 'venedor', 'vent', 'veracitat',
  'verb', 'verdura', 'veredicte', 'veritat', 'vermellor', 'vers', 'vertical', 'vespre',
  'vessant', 'vestigi', 'veterinari', 'vetlla', 'veueta', 'viabilitat', 'vianant', 'viatge',
  'vibrant', 'vicissitud', 'vida', 'vident', 'vidrier', 'vigilant', 'vigor', 'vinagre',
  'vincle', 'vint', 'violinista', 'virrei', 'virtut', 'visera', 'visita', 'vistiplau',
  'visual', 'vitalitat', 'vitrina', 'vivacitat', 'vivenda', 'vocal', 'volant', 'voltant',
  'voluntat', 'vora', 'vorera', 'vori', 'votant', 'vuit', 'vulgar', 'xafarderia',
  'xalet', 'xaman', 'xandall', 'xapa', 'xarop', 'xarxa', 'xaval', 'xemeneia',
  'xerif', 'xerraire', 'xiclet', 'xifra', 'ximple', 'xinxeta', 'xiprer', 'xiquet',
  'xisclet', 'xiulet', 'xivarri', 'xocolata', 'xofer', 'zebra', 'zero', 'zona',
]

export const WORDLIST_META: {
  readonly source: string
  readonly licence: string
  readonly generatedAt: string
  readonly wordCount: 2048
  readonly bitsPerWord: 11
} = {
  source: 'https://raw.githubusercontent.com/Softcatala/catalan-dict-tools/master/resultats/lt/diccionari.txt',
  licence:
    'Diccionari català de Softcatalà (projecte catalan-dict-tools), amb llicència dual GNU GPL v2 o posterior i GNU LGPL v2.1 o posterior. Del mateix dipòsit surten el diccionari arrel de noms i la taula de freqüències d’ús, emprats per descartar tecnicismes i per ordenar els candidats.',
  generatedAt: '2026-09-12',
  wordCount: 2048,
  bitsPerWord: 11,
}
